---
# tasks file for deploy_apache_web
  - name: "Check and Print My OS Family"
    debug:
      var: ansible_os_family
  - name: "Check and Print ansible_distribution_version"
    debug:
      var: ansible_distribution_version
  - name: "Check and Print ansible_distribution"
    debug:
      var: ansible_distribution
  - block:
      - name: Install Apache,Redis,PostgreSQL for RedHat
        yum:
          name: "{{ item }}"
          state: latest
          update_cache: yes
        loop:
          - "httpd"
          - "redis"
          - "postgresql"
      - name: "Start My Web Servers evry boot"
        service:
          name: httpd
          state: started
          enabled: yes
    when: ansible_os_family == "RedHat"
  - block:
      - name: "Install Apache,Redis,PostgreSQL for Debian"
        apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
        loop:
          - "redis"
          - "apache2"
          - "postgresql"
      - name: "Start My Web Server evry boot"
        service:
          name: apache2
          state: started
          enabled: yes
    when: ansible_os_family == "Debian"

  - name: "Generate file INDEX.HTML"
    template:
      src=index.j2
      dest={{ destin_folder }}/index.html
      mode=0555

  - name: Copy my Home page to my servers"
    copy:
      src: "{{ item }}"
      dest: "{{ destin_folder }}"
      mode: '0555'
    loop:
      - "ru.png"
      - "ru1.png"
      - "ru3.png"
      - "ru4.png"
      - "ru5.png"
    notify:
      - Restart Apache os_family RedHat
      - Restart Apache os_family Debian

