---
- name: Loops plybook
  hosts: 192.168.0.107
  become: true
  tasks:
  
  - name: Say Hello to All
    debug:
      msg: "Hello {{ item }}"
    loop:
       - "Vasya"
       - "Petya"
       - "Vika"
       - "Katya"
       - "Masha"        

  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZ") == false

  - name: Print Final Output
    debug:
      var: output.stdout
