---
- name: "Update and Upgrade apt and yum packages"
  hosts: all
  become: yes
  tasks:
  
  - name: Update and Upgrade apt Debian packeges
    apt:
      upgrade: "yes"
      update_cache: yes
    when: ansible_os_family == 'Debian'

  - name: Update and Upgrade yum RedHat packeges
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_os_family == 'RedHat'
