---
- hosts: all
  become: yes
  tasks:

  - name: Print and check OS Family
    debug:
      var: ansible_os_family
  
  - name: Restart Apache Web Server For RedHat
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == 'RedHat'

  - name: Restart Apache For Debian
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == 'Debian'
