---
- name: "Install Apache, Enable Apache and Deploy to my wev servers"
  hosts: all
  become: true
  
  vars:
    source_folder: /root/MyWebSite
    destin_folder: /var/www/html

  tasks:
  - debug:  
      var: ansible_os_family
   
  - block: #---------------BLOCK FOR REDHAT-------------------
      - name: "Install Apache"
        yum:
          name: "{{ item }}"
          state: latest
        loop:
           - "httpd"
           - "php"
           
      - name: " Start Apache and Enable at evry boot"
        service:
          name: httpd
          state: started
          enabled: yes
          
    when: ansible_os_family == "RedHat"
    
  - block: #---------------BLOCK FOR DEBIAN-----------------------
    
      - name: "Install Apache"
        apt:
          name: "{{ item }}"
          state: latest
        with_items:
          - "apache2"
          - "php"
  
      - name: "Start Apache and Enable at evry boot" 
        service:
          name: apache2
          state: started 
          enabled: yes
               
    when: ansible_os_family == "Debian"

  - name: "Copy my Web Site to my WEB Servers"
    copy:
      src: "{{ item }}"
      dest: "{{ destin_folder }}"
      mode: 0555       
    with_fileglob: "{{ source_folder }}/*"  
    notify:
      - Restart Apache RedHat
      - Restart Apache Debian
      
  - name: "Generate index.html"
    template:
      src: "{{ source_folder }}/index.j2"
      dest: "{{ destin_folder }}/index.html"
      mode: 0555
    notify: 
      - Restart Apache RedHat
      - Restart Apache Debian      
        
  handlers:
  - name: Restart Apache RedHat
    service:
      name: httpd
      state: restarted
      
  - name: Restart Apache Debian
    service:
      name: apache2
      state: restarted
