---
# handlers file for deploy_apache_web
- name: Restart Apache os_family RedHat
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"

- name: Restart Apache os_family Debian
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"
